apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-heolink
  annotations:
    "store.halo.run/app-id": "app-acJAD"
spec:
  displayName: HeoLink
  author:
    name: 张洪Heo
    website: "https://github.com/zhheo"
  description: 基于Halo的导航主题
  logo: "https://img.zhheo.com/i/2024/05/21/664c1adb3412e.webp"
  homepage: "https://github.com/zhheo/halo-theme-heolink#readme"
  repo: "https://github.com/zhheo/halo-theme-heolink"
  issues: "https://github.com/zhheo/halo-theme-heolink/issues"
  settingName: "theme-heolink-setting"
  configMapName: "theme-heolink-configMap"
  version: "0.11.2"
  requires: ">=2.20.0"
  license:
    - name: "Apache-2.0"
      url: "https://github.com/zhheo/halo-theme-heolink/blob/main/LICENSE"
