apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-heolink
spec:
  displayName: HeoLink
  author:
    name: 张洪Heo
    website: "https://github.com/zhheo"
  description: 基于Halo的导航主题
  logo: "https://bu.dusays.com/2024/05/16/66457a55ce6e3.png"
  homepage: "https://github.com/zhheo/halo-theme-heolink#readme"
  repo: "https://github.com/zhheo/halo-theme-heolink"
  issues: "https://github.com/zhheo/halo-theme-heolink/issues"
  settingName: "theme-heolink-setting"
  configMapName: "theme-heolink-configMap"
  version: "1.0.0"
  requires: ">=2.15.0"
  license:
    - name: "Apache-2.0"
      url: "https://github.com/zhheo/halo-theme-heolink/blob/main/LICENSE"
